on:
  push:
    branches: [master]

name: Azure Container Instance Deployment

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build ./WebApi -t jumindju/bor-web-api:${{ github.sha }}
            docker push jumindju/bor-web-api:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: bor-web-api
            image: jumindju/bor-web-api:${{ github.sha }}
            cpu: 1
            memory: 1
            name: bor-web-api
            location: 'west europe'
